### ISSUE TITLE
Comments next to imports are duplicated

### ISSUE THREAD

**Issue by juanrfigueiredo** [ecsbjunior/prettier-plugin-fort-imports#1]
![example](https://media.discordapp.net/attachments/1105913377039061084/1159190559936757890/image.png?ex=651efbd6&is=651daa56&hm=dc45a9d596185c89f4d3b010a07dd27dbd7df7f1e4931270f59d40261e8ade26&=)

**Comment by ecsbjunior** [comment]
resolved
